version: '2'
services:
  webserver:
    container_name: webserver
    build: 
      context: .
      dockerfile: /php/Dockerfile
    volumes:
    - "~/phpsqlsrv/www:/var/www/html"
    ports:
    - 80:80
    - 443:443
  database:
    container_name: database
    build: 
      context: .
      dockerfile: /mssql/Dockerfile
    volumes:
    - "~/phpsqlsrv/backup:/var/opt/mssql/backup"
    ports:
    - 1433:1433
